version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ABI03plr
    networks:
      - spring-net

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"  # This is for external tools (e.g. MySQL Workbench), not your app
    environment:
      MYSQL_ROOT_PASSWORD: ABI03plr
      MYSQL_DATABASE: demo
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pABI03plr"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  spring-net:
