version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-1.cluster-cl8emquo6se4.eu-north-1.rds.amazonaws.com:3306/database-1?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password  # 🔁 Replace with actual RDS password
    networks:
      - spring-net

networks:
  spring-net:
